# Site settings
title: opengl-tutorial
email: contact@opengl-tutorial.org
url: "http://www.opengl-tutorial.org"
description: "Free tutorials for modern Opengl (3.3 and later) in C/C++"
baseurl: ""
highlighter: pygments
safe: true
lsi: false
source:      .
languages_iso: [en, zh, ja, ru, fr]
languages: [en, cn, jp, ru, fr]
languages_names: [english, chinese, japanese, russian, français]
# Build settings
markdown: kramdown
permalink: pretty
